/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Day {
  'dayOfWeek' : bigint,
  'exercises' : Array<Exercise>,
  'dayLabel' : string,
}
export interface Exercise {
  'name' : string,
  'sets' : bigint,
  'targetReps' : bigint,
  'targetWeight' : number,
}
export interface LogEntry {
  'setNumber' : bigint,
  'weight' : number,
  'reps' : bigint,
  'completed' : boolean,
  'exerciseName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutPlan {
  'id' : string,
  'owner' : Principal,
  'days' : Array<Day>,
  'name' : string,
}
export interface WorkoutSession {
  'id' : string,
  'planId' : string,
  'owner' : Principal,
  'date' : string,
  'logs' : Array<LogEntry>,
  'dayLabel' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSession' : ActorMethod<[WorkoutSession], undefined>,
  'createWorkoutPlan' : ActorMethod<[WorkoutPlan], undefined>,
  'deleteWorkoutPlan' : ActorMethod<[string], undefined>,
  'getAllOwnWorkoutPlans' : ActorMethod<[], Array<WorkoutPlan>>,
  'getAllSessions' : ActorMethod<[], Array<WorkoutSession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSessionByDate' : ActorMethod<[string], Array<WorkoutSession>>,
  'getSessionsByPlan' : ActorMethod<[string], Array<WorkoutSession>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkoutPlanById' : ActorMethod<[string], [] | [WorkoutPlan]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateSessionLog' : ActorMethod<[string, LogEntry], undefined>,
  'updateWorkoutPlan' : ActorMethod<[WorkoutPlan], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];