/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LogEntry = IDL.Record({
  'setNumber' : IDL.Nat,
  'weight' : IDL.Float64,
  'reps' : IDL.Nat,
  'completed' : IDL.Bool,
  'exerciseName' : IDL.Text,
});
export const WorkoutSession = IDL.Record({
  'id' : IDL.Text,
  'planId' : IDL.Text,
  'owner' : IDL.Principal,
  'date' : IDL.Text,
  'logs' : IDL.Vec(LogEntry),
  'dayLabel' : IDL.Text,
});
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'sets' : IDL.Nat,
  'targetReps' : IDL.Nat,
  'targetWeight' : IDL.Float64,
});
export const Day = IDL.Record({
  'dayOfWeek' : IDL.Nat,
  'exercises' : IDL.Vec(Exercise),
  'dayLabel' : IDL.Text,
});
export const WorkoutPlan = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'days' : IDL.Vec(Day),
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSession' : IDL.Func([WorkoutSession], [], []),
  'createWorkoutPlan' : IDL.Func([WorkoutPlan], [], []),
  'deleteWorkoutPlan' : IDL.Func([IDL.Text], [], []),
  'getAllOwnWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSessionByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkoutSession)],
      ['query'],
    ),
  'getSessionsByPlan' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkoutSession)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkoutPlanById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WorkoutPlan)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'updateSessionLog' : IDL.Func([IDL.Text, LogEntry], [], []),
  'updateWorkoutPlan' : IDL.Func([WorkoutPlan], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LogEntry = IDL.Record({
    'setNumber' : IDL.Nat,
    'weight' : IDL.Float64,
    'reps' : IDL.Nat,
    'completed' : IDL.Bool,
    'exerciseName' : IDL.Text,
  });
  const WorkoutSession = IDL.Record({
    'id' : IDL.Text,
    'planId' : IDL.Text,
    'owner' : IDL.Principal,
    'date' : IDL.Text,
    'logs' : IDL.Vec(LogEntry),
    'dayLabel' : IDL.Text,
  });
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'sets' : IDL.Nat,
    'targetReps' : IDL.Nat,
    'targetWeight' : IDL.Float64,
  });
  const Day = IDL.Record({
    'dayOfWeek' : IDL.Nat,
    'exercises' : IDL.Vec(Exercise),
    'dayLabel' : IDL.Text,
  });
  const WorkoutPlan = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'days' : IDL.Vec(Day),
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSession' : IDL.Func([WorkoutSession], [], []),
    'createWorkoutPlan' : IDL.Func([WorkoutPlan], [], []),
    'deleteWorkoutPlan' : IDL.Func([IDL.Text], [], []),
    'getAllOwnWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSessionByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkoutSession)],
        ['query'],
      ),
    'getSessionsByPlan' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkoutSession)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkoutPlanById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WorkoutPlan)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'updateSessionLog' : IDL.Func([IDL.Text, LogEntry], [], []),
    'updateWorkoutPlan' : IDL.Func([WorkoutPlan], [], []),
  });
};

export const init = ({ IDL }) => { return []; };